### PR TITLE
Add a Fee Handle for the last hop

### PR DESCRIPTION
**Pull request by ziggie1984**

### CODE REVIEW

**Comment by rkfg** [comment]
Please write detailed description of the feature. Why do we need it? We have plenty of fee limiters already.

**Comment by ziggie1984** [comment]
Some Channels like Kraken for example, they will increase there fee on the channel when more then 10% of outbound (speaking from my perspective) are present from 100ppm to 500 ppm, although this only happens 30-35 min after this state is present. Therefore I would like to control the rebalance of this channel, but only if the fee of kraken is still in the range of 100 ppm. Initial Feature Request came from bitcoinite.

**Comment by ziggie1984** [comment]
But maybe too edge-casy ....

**Comment by rkfg** [comment]
The same can happen to any channel along the route. Why make the last hop that special? We already have `--fee-limit-ppm`, use that and specify `--to` explicitly. If the target channel fee is too high it will fail.

**Comment by ziggie1984** [comment]
I agree, lets discard that

**Pull request closed without merging**
