### PR TITLE
add scid and change to and from to arrays

### PR DESCRIPTION
**Pull request by ziggie1984**
Hi, I like this project a lot, really nice and efficient rebalancer 👍 .

This PR wants to also allow Short Channel Ids in the format of "539268x845x1", to allow for more flexible channel selection. Personally I am using bos-tool or Thunderhub and it shows only the scid. I changed the uint64 arrays to string arrays to avoid having two arrays for channelId.

In addition this change includes the feature for #7 

Thanks in advance for looking to this PR, if you don't like it just ignore it.

### CODE REVIEW

**Comment by rkfg** [comment]
Thank you, looks great! However, I'm a bit concerned about the channel parameter type change from uint64 to string. It means the config would stop working until updated. I think JSON config can be migrated automatically but TOML can't because it can contain comments (which was the primary reason to add its support) so simply loading and saving it back would delete them. Can you please check if it's possible to somehow accept both numbers and strings at the cost of slight code complexity increase? I think parsing into `[]any` and then processing the array with a type switch could work.

**Comment by ziggie1984** [comment]
Yes its possible to have both datatypes in there, although for toml the user will need to create a homogeneous array otherwise the parser  will complain, json on the otherhand allows mixed values. Will change now

**Comment by ziggie1984** [comment]
So now everything remains compatible with prior versions, thanks for this good input! For the toml files only on format will be allowed which makes the change backwards-compatible, for json everything is a string anyways in the background

**Comment by rkfg** [comment]
Great, now all that's left is fixing the descriptions as I marked in the reviews. The rest looks good, I'll test it on the weekend.

**Comment by ziggie1984** [comment]
Hmm I did not see any comments in the code. Though there is another problem, somehow the cmd parser is not able to read  elements when using the `any` parameter, so looks like now everything except using the commandline works. So I guess this solution is not right either. Also tried with a single any type, the commandline parses always a <nil>, I guess its hard for the parser to check what's been parsing when the type is any ?

So I guess using any is not really a good idea for the commandline inputs

**Comment by ziggie1984** [comment]
maybe an additional --ExcludeChannelsInScid field for example where they could be used instead of the normal id. But disadvantage would be that we are bloating the argument set.

Regarding the old approach you mean toml user would need to update the config file to remain compatible and that could disrupt some noderunners software right ?

**Comment by rkfg** [comment]
> Hmm I did not see any comments in the code.

Scroll up, does this not show for you? 


> maybe the best solution would be to just add another handle for each option where we allow both and let them exist in parallel ?

What would it look like?

**Review by rkfg — CHANGES_REQUESTED** [review]

**Comment by rkfg** [comment]
Should work now, I never used this review tool before as the owner I admit 😅

**Comment by ziggie1984** [comment]
Sounds good will split it into two :)

**Comment by ziggie1984** [comment]
> What would it look like?

Normally we have to add the scid option for each flag which allows channel_ids, so could bloat the flag set very fast. Though we could maybe signal deprecating of the old flags which only allow number as channelID ?

**Comment by rkfg** [comment]
That would work but it'll leave us with longer options and parameters as the only choice. For example, instead of `--from` we'd need to use `--from-scid` and for excludes it's even longer. How about we switch to `[]string` but add a temporary validation code that checks the parameter type in the config and if it's `uint64` it shows an error and migration instructions, then exits? The main problem is cryptic errors when types don't match, it's better to tell the user what's wrong and how to fix it. Then after some versions we can drop it. I don't think a lot of people use this program right now but nevertheless it's important to care about those who do.

**Comment by ziggie1984** [comment]
Ok sounds good, for the --to and --from field should we do it in this PR too bc we are gonna change it to string anyways ?

**Comment by rkfg** [comment]
If it's not hard, for clarity let's keep from/to as `[]uint64` in this PR and then update and validate everything as strings in the other one.

**Comment by ziggie1984** [comment]
Rebased and added concrete error message when int instead of string is used

**Review by rkfg — COMMENTED** [review]
The code LGTM so far, will test it on my real config. Thanks!

**Pull request merged**
