### PR TITLE
Add relative source/target amounts, part of #3

### PR DESCRIPTION
**Pull request by rkfg**
Allow specifying a fraction of source/target channel capacity as the desired limit for amount calculation.

### CODE REVIEW

**Comment by rkfg** [comment]
@TrezorHannes please check this PR and see if it's what you wanted in #3. I tested on a few of my channels targeting both local and remote balance, seems to be correct but who knows! Infinite rebalances are coming later if everything's okay with this.

**Comment by rkfg** [comment]
Now that amounts can be very different on every try I think it's time to add invoice cache (a map like amount => invoice). No idea how big they are in the lnd's database but why pollute it further when we can prevent it.

**Comment by rkfg** [comment]
Been testing it for a while, seems to be working fine.

**Comment by TrezorHannes** [comment]
This seems to be working well. Need to do some calculations if it's taking the percentage target into consideration, but it's hard to do while it's running. Will think about how to report this properly. Thanks so much for implementing this!

**Comment by rkfg** [comment]
Yes, I use this option often and it works well. If it doesn't rebalance the full expected amount it's usually because the source channel doesn't have enough liquidity with respect to other restrictions (like the default 50%).

**Pull request merged**
