### PR TITLE
Show ppm for Rebalance Requests

### PR DESCRIPTION
**Pull request by ziggie1984**
I find it useful to add the PPM right besides the Fee when Printing the route, maybe it aligns with you objectives, thanks for taking a look.

(build on top of all the other branches, should rebase them all on master?)

```
2022/10/12 17:37:13 Attempt #1, amount: 40000 (max fee: 16 sat | 400 ppm )
Total fee: 14 sat | 359 ppm
```

### CODE REVIEW

**Comment by rkfg** [comment]
Appreciate the improvements but looks like these PRs got all mixed together. Usually there should be separate branches for every feature and those branches should be based on `master`.

**Comment by rkfg** [comment]
Also, how about adding this ppm to the success message? Sometimes it's the same as the attempt but sometimes it happens after probing so the numbers could be very different (due to base fees >0 on the route). I even had a situation when the channel fee changed right during probing, it was zero on the regular attempt but raised while probing. The end result was still within the fee limits of course but it was unexpected.

**Comment by ziggie1984** [comment]
Sounds good, I did everything ontop of the new changes to securely and easily test the next change (was using scid and fee-limit) already, but sure I can put them all on master so everything is a new change. 

Yes I think its a good idea to add them also to the probing messages and success messages, will add that

**Comment by rkfg** [comment]
My protip 😄: start a separate temporary `dev` branch locally, then create a new branch on `master` (and rebase when needed) for every feature you want to merge, then cherry-pick commits from your `dev` to those feature branches, squash small fixes on them, then force-push. However, it might get messy if different features change the same lines or rely on each other so there's no silver bullet.

Let me know when it's ready!

**Comment by rkfg** [comment]
I decided to merge it now, the success message is a minor detail and I can add it myself. Thank you!

**Comment by ziggie1984** [comment]
ok thanks, was busy this week, but will follow your git pro-tip for the next contributions. 👍

**Pull request merged**
